# Generated by Django 3.0.1 on 2019-12-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191220_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyrule',
            name='maxAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
