# Generated by Django 3.0.1 on 2019-12-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20191220_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyrule',
            name='id',
        ),
        migrations.AddField(
            model_name='policyrule',
            name='uid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
