# Generated by Django 3.0.1 on 2019-12-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20191220_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyrule',
            old_name='uid',
            new_name='id',
        ),
    ]
