# Generated by Django 2.1 on 2019-12-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20191220_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrule',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policyrule',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
