# Generated by Django 2.1 on 2019-12-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20191222_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrule',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='policyrule',
            name='uid',
            field=models.IntegerField(unique=True),
        ),
    ]
